---
version: 2
jobs:
  node-latest: &test
    docker:
      - image: node:latest
    working_directory: ~/cli
    steps:
      - checkout
      - restore_cache: &restore_cache
          keys:
            - v0-yarn-{{checksum ".circleci/config.yml"}}-{{ .Branch }}-{{checksum "yarn.lock"}}
            - v0-yarn-{{checksum ".circleci/config.yml"}}-{{ .Branch }}-
            - v0-yarn-{{checksum ".circleci/config.yml"}}-master-
      - run: yarn
      - run: yarn test
      - store_test_results: &store_test_results
          path: ~/cli/reports
      - save_cache: &save_cache
          key: v0-yarn-{{checksum ".circleci/config.yml"}}-{{ .Branch }}-{{checksum "yarn.lock"}}
          paths:
            - ~/cli/node_modules
            - /usr/local/share/.cache/yarn
            - /usr/local/share/.config/yarn
  node-10:
    <<: *test
    docker:
      - image: node:10
    steps:
      - checkout
      - restore_cache: *restore_cache
      - run: yarn
      - run: yarn test
      - store_test_results: *store_test_results
  node-12:
    <<: *test
    docker:
      - image: node:12
    steps:
      - checkout
      - restore_cache: *restore_cache
      - run: yarn
      - run: yarn test
      - store_test_results: *store_test_results
  release:
    <<: *test
    steps:
      - add_ssh_keys
      - checkout
      - restore_cache: *restore_cache
      - run: .circleci/release

workflows:
  version: 2
  "@oclif/nyc-config":
    jobs:
      - node-latest
      - node-10
      - node-12
      - release:
          context: org-global
          filters:
            branches: {only: master}
          requires:
            - node-latest
            - node-10
            - node-12
